import type { iTrabajos } from "./interfaces.ts"

export const trabajos: iTrabajos = {
  "bahia01": {
    nombre: "Bahia Confort",
    lugar: "mitre-casanova",
    categoria: "Apart Hotel",
    portada: "/assets/gallery/bahia1/bahiaconfort01.webp",
    logo: "./assets/logos/bahia_confort.svg",
    galeria: [
      "/assets/gallery/bahia1/bahiaconfort01.webp",
      "/assets/gallery/bahia1/bahiaconfort02.webp",
      "/assets/gallery/bahia1/bahiaconfort03.webp",
      "/assets/gallery/bahia1/bahiaconfort04.webp",
      "/assets/gallery/bahia1/bahiaconfort05.webp",
      "/assets/gallery/bahia1/bahiaconfort06.webp",
      "/assets/gallery/bahia1/bahiaconfort07.webp",
      "/assets/gallery/bahia1/bahiaconfort08.webp",
      "/assets/gallery/bahia1/bahiaconfort09.webp",
      "/assets/gallery/bahia1/bahiaconfort10.webp",
      "/assets/gallery/bahia1/bahiaconfort11.webp",
      "/assets/gallery/bahia1/bahiaconfort12.webp",
      "/assets/gallery/bahia1/bahiaconfort13.webp",
      "/assets/gallery/bahia1/bahiaconfort14.webp",
      "/assets/gallery/bahia1/bahiaconfort15.webp",
      "/assets/gallery/bahia1/bahiaconfort16.webp",
    ],
    tour: ""
  },
  "orion01": {
    nombre: "Hotel Orion",
    lugar: "españa",
    categoria: "Apart Hotel",
    portada: "/assets/gallery/orion1/orion0.webp",
    logo: "./assets/logos/hotel_orion.svg",
    galeria: [
      "/assets/gallery/orion1/orion0.webp",
      "/assets/gallery/orion1/orion1.webp",
      "/assets/gallery/orion1/orion2.webp",
      "/assets/gallery/orion1/orion3.webp",
      "/assets/gallery/orion1/orion4.webp",
      "/assets/gallery/orion1/orion5.webp",
      "/assets/gallery/orion1/orion6.webp",
      "/assets/gallery/orion1/orion7.webp",
      "/assets/gallery/orion1/orion8.webp",
      "/assets/gallery/orion1/orion9.webp",
    ],
    tour: ""
  },
  "alem01": {
    nombre: "Punto Alem",
    lugar: "alem",
    categoria: "Salones",
    portada: "/assets/logos/punto_alem.svg",
    logo: "./assets/logos/punto_alem.svg",
    galeria: [],
    tour: "https://kuula.co/share/collection/7bq00?logo=1&info=1&fs=1&vr=0&zoom=1&gyro=0&autorotate=0.3&thumbs=1&alpha=0.60&inst=es"
  },
  "top501": {
    nombre: "Top 5",
    lugar: "san-martin",
    categoria: "Salones",
    portada: "/assets/logos/top5.svg",
    logo: "./assets/logos/top5.svg",
    galeria: [],
    tour: "https://kuula.co/share/collection/7bPvP?logo=1&info=1&fs=1&vr=0&zoom=1&gyro=0&autorotate=0.3&thumbs=1&alpha=0.60&inst=es",
  },
  "top601": {
    nombre: "Top 6",
    lugar: "charlone",
    categoria: "Salones",
    portada: "/assets/logos/top6.svg",
    logo: "./assets/logos/top6.svg",
    galeria: [],
    tour: "",
  },
  "casali00": {
    nombre: "Casali Prop",
    lugar: "monte-hermoso01",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali0/casaliprop6.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali0/casaliprop1.webp",
      "/assets/gallery/casali0/casaliprop2.webp",
      "/assets/gallery/casali0/casaliprop3.webp",
      "/assets/gallery/casali0/casaliprop4.webp",
      "/assets/gallery/casali0/casaliprop5.webp",
      "/assets/gallery/casali0/casaliprop6.webp",
      "/assets/gallery/casali0/casaliprop7.webp",
    ],
    tour: "https://kuula.co/share/collection/7XJmF?logo=1&info=1&fs=1&vr=0&zoom=1&gyro=0&autorotate=0.3&thumbs=1&alpha=0.60&inst=es",
  },
  "casali01": {
    nombre: "Casali Prop",
    lugar: "saihueche",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali1/casaliprop1.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali1/casaliprop1.webp",
      "/assets/gallery/casali1/casaliprop2.webp",
      "/assets/gallery/casali1/casaliprop3.webp",
      "/assets/gallery/casali1/casaliprop4.webp",
      "/assets/gallery/casali1/casaliprop5.webp",
      "/assets/gallery/casali1/casaliprop6.webp",
      "/assets/gallery/casali1/casaliprop7.webp",
    ],
    tour: "",
  },
  "casali02": {
    nombre: "Casali Prop",
    lugar: "balboa",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali2/casaliprop1.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali2/casaliprop1.webp",
      "/assets/gallery/casali2/casaliprop2.webp",
      "/assets/gallery/casali2/casaliprop3.webp",
      "/assets/gallery/casali2/casaliprop4.webp",
      "/assets/gallery/casali2/casaliprop5.webp",
      "/assets/gallery/casali2/casaliprop6.webp",
      "/assets/gallery/casali2/casaliprop7.webp",
    ],
    tour: "",
  },
  "casali03": {
    nombre: "Casali Prop",
    lugar: "patagonia01",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali3/casaliprop11.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali3/casaliprop01.webp",
      "/assets/gallery/casali3/casaliprop02.webp",
      "/assets/gallery/casali3/casaliprop03.webp",
      "/assets/gallery/casali3/casaliprop04.webp",
      "/assets/gallery/casali3/casaliprop05.webp",
      "/assets/gallery/casali3/casaliprop06.webp",
      "/assets/gallery/casali3/casaliprop07.webp",
      "/assets/gallery/casali3/casaliprop08.webp",
      "/assets/gallery/casali3/casaliprop09.webp",
      "/assets/gallery/casali3/casaliprop10.webp",
      "/assets/gallery/casali3/casaliprop11.webp",
    ],
    tour: "",
  },
  "casali04": {
    nombre: "Casali Prop",
    lugar: "monte-hermoso02",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali4/casaliprop04.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali4/casaliprop01.webp",
      "/assets/gallery/casali4/casaliprop02.webp",
      "/assets/gallery/casali4/casaliprop03.webp",
      "/assets/gallery/casali4/casaliprop04.webp",
      "/assets/gallery/casali4/casaliprop05.webp",
      "/assets/gallery/casali4/casaliprop06.webp",
      "/assets/gallery/casali4/casaliprop07.webp",
      "/assets/gallery/casali4/casaliprop08.webp",
      "/assets/gallery/casali4/casaliprop09.webp",
      "/assets/gallery/casali4/casaliprop10.webp",
      "/assets/gallery/casali4/casaliprop11.webp",
      "/assets/gallery/casali4/casaliprop12.webp",
      "/assets/gallery/casali4/casaliprop13.webp",
      "/assets/gallery/casali4/casaliprop14.webp",
    ],
    tour: "",
  },
  "casali05": {
    nombre: "Casali Prop",
    lugar: "patagonia02",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali5/casaliprop1.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali5/casaliprop1.webp",
      "/assets/gallery/casali5/casaliprop2.webp",
      "/assets/gallery/casali5/casaliprop3.webp",
      "/assets/gallery/casali5/casaliprop4.webp",
      "/assets/gallery/casali5/casaliprop5.webp",
      "/assets/gallery/casali5/casaliprop6.webp",
      "/assets/gallery/casali5/casaliprop7.webp",
    ],
    tour: "",
  },
  "casali06": {
    nombre: "Casali Prop",
    lugar: "punta-este",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali6/casaliprop03.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali6/casaliprop01.webp",
      "/assets/gallery/casali6/casaliprop02.webp",
      "/assets/gallery/casali6/casaliprop03.webp",
      "/assets/gallery/casali6/casaliprop04.webp",
      "/assets/gallery/casali6/casaliprop05.webp",
      "/assets/gallery/casali6/casaliprop06.webp",
      "/assets/gallery/casali6/casaliprop07.webp",
      "/assets/gallery/casali6/casaliprop08.webp",
      "/assets/gallery/casali6/casaliprop09.webp",
      "/assets/gallery/casali6/casaliprop10.webp",
      "/assets/gallery/casali6/casaliprop11.webp",
      "/assets/gallery/casali6/casaliprop12.webp",
      "/assets/gallery/casali6/casaliprop13.webp",
    ],
    tour: "https://kuula.co/share/collection/7cpLQ?logo=1&info=1&fs=1&vr=0&zoom=1&gyro=0&autorotate=0.49&thumbs=1&alpha=0.60&inst=es",
  },
  "casali07": {
    nombre: "Casali Prop",
    lugar: "soler88",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali7/casaliprop01.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali7/casaliprop01.webp",
      "/assets/gallery/casali7/casaliprop02.webp",
      "/assets/gallery/casali7/casaliprop03.webp",
      "/assets/gallery/casali7/casaliprop04.webp",
      "/assets/gallery/casali7/casaliprop05.webp",
      "/assets/gallery/casali7/casaliprop06.webp",
      "/assets/gallery/casali7/casaliprop07.webp",
      "/assets/gallery/casali7/casaliprop08.webp",
      "/assets/gallery/casali7/casaliprop09.webp",
      "/assets/gallery/casali7/casaliprop10.webp",
      "/assets/gallery/casali7/casaliprop11.webp",
    ],
    tour: "https://kuula.co/share/collection/7JZxx?logo=1&info=1&fs=0&vr=0&zoom=1&gyro=0&autorotate=0.39&autop=10&thumbs=1&alpha=0.60&inst=es",
  },
  "casali08": {
    nombre: "Casali Prop",
    lugar: "caleu-caleu",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali8/casaliprop01.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali8/casaliprop01.webp",
      "/assets/gallery/casali8/casaliprop02.webp",
      "/assets/gallery/casali8/casaliprop03.webp",
      "/assets/gallery/casali8/casaliprop04.webp",
      "/assets/gallery/casali8/casaliprop05.webp",
      "/assets/gallery/casali8/casaliprop06.webp",
      "/assets/gallery/casali8/casaliprop07.webp",
      "/assets/gallery/casali8/casaliprop08.webp",
      "/assets/gallery/casali8/casaliprop09.webp",
      "/assets/gallery/casali8/casaliprop10.webp",
      "/assets/gallery/casali8/casaliprop11.webp",
      "/assets/gallery/casali8/casaliprop12.webp",
      "/assets/gallery/casali8/casaliprop13.webp",
      "/assets/gallery/casali8/casaliprop14.webp",
      "/assets/gallery/casali8/casaliprop15.webp",
      "/assets/gallery/casali8/casaliprop16.webp",
      "/assets/gallery/casali8/casaliprop17.webp",
      "/assets/gallery/casali8/casaliprop18.webp",
      "/assets/gallery/casali8/casaliprop19.webp",
      "/assets/gallery/casali8/casaliprop20.webp",
    ],
    tour: "https://kuula.co/share/collection/7ccS7?logo=1&info=1&fs=1&vr=0&zoom=1&gyro=0&autorotate=0.3&thumbs=1&alpha=0.60&inst=es",
  },
  "casali09": {
    nombre: "Casali Prop",
    lugar: "alem823",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali9/casaliprop01.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali9/casaliprop01.webp",
      "/assets/gallery/casali9/casaliprop02.webp",
      "/assets/gallery/casali9/casaliprop03.webp",
      "/assets/gallery/casali9/casaliprop04.webp",
      "/assets/gallery/casali9/casaliprop05.webp",
      "/assets/gallery/casali9/casaliprop06.webp",
      "/assets/gallery/casali9/casaliprop07.webp",
      "/assets/gallery/casali9/casaliprop08.webp",
      "/assets/gallery/casali9/casaliprop09.webp",
      "/assets/gallery/casali9/casaliprop10.webp",
      "/assets/gallery/casali9/casaliprop11.webp",
      "/assets/gallery/casali9/casaliprop12.webp",
      "/assets/gallery/casali9/casaliprop13.webp",
      "/assets/gallery/casali9/casaliprop14.webp",
      "/assets/gallery/casali9/casaliprop15.webp",
      "/assets/gallery/casali9/casaliprop16.webp",
      "/assets/gallery/casali9/casaliprop17.webp",
      "/assets/gallery/casali9/casaliprop18.webp",
      "/assets/gallery/casali9/casaliprop19.webp",
      "/assets/gallery/casali9/casaliprop20.webp",
      "/assets/gallery/casali9/casaliprop21.webp",
    ],
    tour: "https://kuula.co/share/collection/7ck0h?logo=1&info=1&fs=1&vr=0&zoom=1&gyro=0&autorotate=0.3&thumbs=1&alpha=0.60&inst=es",
  },
  "casali10": {
    nombre: "Casali Prop",
    lugar: "cooperacion2",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali10/casaliprop01.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali10/casaliprop01.webp",
      "/assets/gallery/casali10/casaliprop02.webp",
      "/assets/gallery/casali10/casaliprop03.webp",
      "/assets/gallery/casali10/casaliprop04.webp",
      "/assets/gallery/casali10/casaliprop05.webp",
      "/assets/gallery/casali10/casaliprop06.webp",
      "/assets/gallery/casali10/casaliprop07.webp",
      "/assets/gallery/casali10/casaliprop08.webp",
      "/assets/gallery/casali10/casaliprop09.webp",
      "/assets/gallery/casali10/casaliprop10.webp",
      "/assets/gallery/casali10/casaliprop11.webp",
    ],
    tour: "https://kuula.co/share/collection/7ckLX?logo=1&info=1&fs=1&vr=0&zoom=1&gyro=0&autorotate=0.3&thumbs=1&alpha=0.60&inst=es",
  },
  "casali11": {
    nombre: "Casali Prop",
    lugar: "solares-norte",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali11/casaliprop01.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali11/casaliprop01.webp",
      "/assets/gallery/casali11/casaliprop02.webp",
      "/assets/gallery/casali11/casaliprop03.webp",
      "/assets/gallery/casali11/casaliprop04.webp",
      "/assets/gallery/casali11/casaliprop05.webp",
      "/assets/gallery/casali11/casaliprop06.webp",
      "/assets/gallery/casali11/casaliprop07.webp",
      "/assets/gallery/casali11/casaliprop08.webp",
      "/assets/gallery/casali11/casaliprop09.webp",
      "/assets/gallery/casali11/casaliprop10.webp",
      "/assets/gallery/casali11/casaliprop11.webp",
      "/assets/gallery/casali11/casaliprop12.webp",
      "/assets/gallery/casali11/casaliprop13.webp",
      "/assets/gallery/casali11/casaliprop14.webp",
      "/assets/gallery/casali11/casaliprop15.webp",
      "/assets/gallery/casali11/casaliprop16.webp",
      "/assets/gallery/casali11/casaliprop17.webp",
      "/assets/gallery/casali11/casaliprop18.webp",
      "/assets/gallery/casali11/casaliprop19.webp",
      "/assets/gallery/casali11/casaliprop20.webp",
      "/assets/gallery/casali11/casaliprop21.webp",
      "/assets/gallery/casali11/casaliprop22.webp",
      "/assets/gallery/casali11/casaliprop23.webp",
      "/assets/gallery/casali11/casaliprop24.webp",
      "/assets/gallery/casali11/casaliprop25.webp",
      "/assets/gallery/casali11/casaliprop26.webp",
    ],
    tour: "https://kuula.co/share/collection/7cnr0?logo=1&info=1&fs=1&vr=0&zoom=1&gyro=0&autorotate=0.3&thumbs=1&alpha=0.60&inst=es",
  },
  "casali12": {
    nombre: "Casali Prop",
    lugar: "torres-al-mar-11",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali12/casaliprop01.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali12/casaliprop01.webp",
      "/assets/gallery/casali12/casaliprop02.webp",
      "/assets/gallery/casali12/casaliprop03.webp",
      "/assets/gallery/casali12/casaliprop04.webp",
      "/assets/gallery/casali12/casaliprop05.webp",
      "/assets/gallery/casali12/casaliprop06.webp",
      "/assets/gallery/casali12/casaliprop07.webp",
      "/assets/gallery/casali12/casaliprop08.webp",
      "/assets/gallery/casali12/casaliprop09.webp",
      "/assets/gallery/casali12/casaliprop10.webp",
      "/assets/gallery/casali12/casaliprop11.webp",
      "/assets/gallery/casali12/casaliprop12.webp",
      "/assets/gallery/casali12/casaliprop13.webp",
      "/assets/gallery/casali12/casaliprop14.webp",
      "/assets/gallery/casali12/casaliprop15.webp",
      "/assets/gallery/casali12/casaliprop16.webp",
      "/assets/gallery/casali12/casaliprop17.webp",
      "/assets/gallery/casali12/casaliprop18.webp",
      "/assets/gallery/casali12/casaliprop19.webp",

    ],
    tour: "https://kuula.co/share/collection/7cx0d?logo=1&info=1&fs=1&vr=0&zoom=1&gyro=0&autorotate=0.3&thumbs=1&alpha=0.60&inst=es",
  },
  "casali13": {
    nombre: "Casali Prop",
    lugar: "torres-al-mar-5",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali13/casaliprop01.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali13/casaliprop01.webp",
      "/assets/gallery/casali13/casaliprop02.webp",
      "/assets/gallery/casali13/casaliprop03.webp",
      "/assets/gallery/casali13/casaliprop04.webp",
      "/assets/gallery/casali13/casaliprop05.webp",
      "/assets/gallery/casali13/casaliprop06.webp",
      "/assets/gallery/casali13/casaliprop07.webp",
      "/assets/gallery/casali13/casaliprop08.webp",
      "/assets/gallery/casali13/casaliprop09.webp",
      "/assets/gallery/casali13/casaliprop10.webp",
      "/assets/gallery/casali13/casaliprop11.webp",
      "/assets/gallery/casali13/casaliprop12.webp",
      "/assets/gallery/casali13/casaliprop13.webp",
      "/assets/gallery/casali13/casaliprop14.webp",
      "/assets/gallery/casali13/casaliprop15.webp",
    ],
    tour: "https://kuula.co/share/collection/7cxGG?logo=1&info=1&fs=1&vr=0&zoom=1&gyro=0&autorotate=0.3&thumbs=1&alpha=0.60&inst=es",
  },

  "casali14": {
    nombre: "Casali Prop",
    lugar: "CuernavacaA",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali14/casaliprop01.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali14/casaliprop01.webp",
      "/assets/gallery/casali14/casaliprop02.webp",
      "/assets/gallery/casali14/casaliprop03.webp",
      "/assets/gallery/casali14/casaliprop04.webp",
      "/assets/gallery/casali14/casaliprop05.webp",
      "/assets/gallery/casali14/casaliprop06.webp",
      "/assets/gallery/casali14/casaliprop07.webp",
      "/assets/gallery/casali14/casaliprop08.webp",
      "/assets/gallery/casali14/casaliprop09.webp",
      "/assets/gallery/casali14/casaliprop10.webp",
      "/assets/gallery/casali14/casaliprop11.webp",
      "/assets/gallery/casali14/casaliprop12.webp",
      "/assets/gallery/casali14/casaliprop13.webp",
      "/assets/gallery/casali14/casaliprop14.webp",
      "/assets/gallery/casali14/casaliprop15.webp",
      "/assets/gallery/casali14/casaliprop16.webp",
    ],
    tour: "",
  },

  "casali15": {
    nombre: "Casali Prop",
    lugar: "CuarnavacaB",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali15/casaliprop01.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali15/casaliprop01.webp",
      "/assets/gallery/casali15/casaliprop02.webp",
      "/assets/gallery/casali15/casaliprop03.webp",
      "/assets/gallery/casali15/casaliprop04.webp",
      "/assets/gallery/casali15/casaliprop05.webp",
      "/assets/gallery/casali15/casaliprop06.webp",
      "/assets/gallery/casali15/casaliprop07.webp",
      "/assets/gallery/casali15/casaliprop08.webp",
      "/assets/gallery/casali15/casaliprop09.webp",
      "/assets/gallery/casali15/casaliprop10.webp",
      "/assets/gallery/casali15/casaliprop11.webp",
      "/assets/gallery/casali15/casaliprop12.webp",
      "/assets/gallery/casali15/casaliprop13.webp",
    ],
    tour: "",
  },

  "casali16": {
    nombre: "Casali Prop",
    lugar: "LosTroncosA",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali16/casaliprop01.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali16/casaliprop01.webp",
      "/assets/gallery/casali16/casaliprop02.webp",
      "/assets/gallery/casali16/casaliprop03.webp",
      "/assets/gallery/casali16/casaliprop04.webp",
      "/assets/gallery/casali16/casaliprop05.webp",
      "/assets/gallery/casali16/casaliprop06.webp",
      "/assets/gallery/casali16/casaliprop07.webp",
      "/assets/gallery/casali16/casaliprop08.webp",
      "/assets/gallery/casali16/casaliprop09.webp",
      "/assets/gallery/casali16/casaliprop10.webp",
      "/assets/gallery/casali16/casaliprop11.webp",
      "/assets/gallery/casali16/casaliprop12.webp",
      "/assets/gallery/casali16/casaliprop13.webp",
      "/assets/gallery/casali16/casaliprop14.webp",
      "/assets/gallery/casali16/casaliprop15.webp",
    ],
    tour: "",
  },

  "casali17": {
    nombre: "Casali Prop",
    lugar: "LosTroncosB",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali17/casaliprop01.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali17/casaliprop01.webp",
      "/assets/gallery/casali17/casaliprop02.webp",
      "/assets/gallery/casali17/casaliprop03.webp",
      "/assets/gallery/casali17/casaliprop04.webp",
      "/assets/gallery/casali17/casaliprop05.webp",
      "/assets/gallery/casali17/casaliprop06.webp",
      "/assets/gallery/casali17/casaliprop07.webp",
      "/assets/gallery/casali17/casaliprop08.webp",
      "/assets/gallery/casali17/casaliprop09.webp",
      "/assets/gallery/casali17/casaliprop10.webp",
      "/assets/gallery/casali17/casaliprop11.webp",
      "/assets/gallery/casali17/casaliprop12.webp",
      "/assets/gallery/casali17/casaliprop13.webp",
    ],
    tour: "",
  },

  "casali18": {
    nombre: "Casali Prop",
    lugar: "3DeFebrero",
    categoria: "Propiedades",
    portada: "/assets/gallery/casali18/casaliprop01.webp",
    logo: "./assets/logos/casali.svg",
    galeria: [
      "/assets/gallery/casali18/casaliprop01.webp",
      "/assets/gallery/casali18/casaliprop02.webp",
      "/assets/gallery/casali18/casaliprop03.webp",
      "/assets/gallery/casali18/casaliprop04.webp",
      "/assets/gallery/casali18/casaliprop05.webp",
      "/assets/gallery/casali18/casaliprop06.webp",
      "/assets/gallery/casali18/casaliprop07.webp",
      "/assets/gallery/casali18/casaliprop08.webp",
      "/assets/gallery/casali18/casaliprop09.webp",
      "/assets/gallery/casali18/casaliprop10.webp",
      "/assets/gallery/casali18/casaliprop11.webp",
      "/assets/gallery/casali18/casaliprop12.webp",
      "/assets/gallery/casali18/casaliprop13.webp",
    ],
    tour: "",
  },

  "iagro01": {
    nombre: "I.A.G.R.O Inmobiliaria",
    lugar: "iagro",
    categoria: "Comercios",
    portada: "./assets/logos/iagro.svg",
    logo: "./assets/logos/iagro.svg",
    galeria: [
      "/assets/gallery/IAGRO/iagro1.webp",
      "/assets/gallery/IAGRO/iagro2.webp",
      "/assets/gallery/IAGRO/iagro3.webp",
    ],
    tour: "",
  },
  "mini01": {
    nombre: "Fine Art & Minimalismo",
    lugar: "mini01",
    categoria: "Propia",
    portada: "/assets/gallery/Minimalismo/minimal1.webp",
    logo: "",
    galeria: [
      "/assets/gallery/Minimalismo/minimal01.webp",
      "/assets/gallery/Minimalismo/minimal02.webp",
      "/assets/gallery/Minimalismo/minimal03.webp",
      "/assets/gallery/Minimalismo/minimal04.webp",
      "/assets/gallery/Minimalismo/minimal05.webp",
      "/assets/gallery/Minimalismo/minimal06.webp",
      "/assets/gallery/Minimalismo/minimal07.webp",
      "/assets/gallery/Minimalismo/minimal08.webp",
      "/assets/gallery/Minimalismo/minimal09.webp",
      "/assets/gallery/Minimalismo/minimal10.webp",
      "/assets/gallery/Minimalismo/minimal11.webp",
      "/assets/gallery/Minimalismo/minimal12.webp",
    ],
    tour: "",
  },

  "moto01": {
    nombre: "Moto Manía",
    lugar: "moto01",
    categoria: "Comercios",
    portada: "/assets/logos/moto_mania.svg",
    logo: "./assets/logos/moto_mania.svg",
    galeria: [],
    tour: "https://kuula.co/share/collection/7bqKQ?logo=1&info=1&fs=1&vr=0&zoom=1&gyro=0&autorotate=0.3&thumbs=1&alpha=0.60&inst=es",
  },
  "dexter01": {
    nombre: "Dexter",
    lugar: "dexter01",
    categoria: "Comercios",
    portada: "/assets/logos/dexter.svg",
    logo: "./assets/logos/dexter.svg",
    galeria: [],
    tour: "",
  },
  "varoba01": {
    nombre: "Varoba",
    lugar: "varoba01",
    categoria: "Comercios",
    portada: "/assets/logos/varoba.svg",
    logo: "./assets/logos/varoba.svg",
    galeria: [],
    tour: "",
  },
  "ragazzi01": {
    nombre: "Ragazzi",
    lugar: "ragazzi01",
    categoria: "Comercios",
    portada: "/assets/logos/ragazzi.svg",
    logo: "./assets/logos/ragazzi.svg",
    galeria: [],
    tour: "",
  },
  "tekno01": {
    nombre: "Teknomanía",
    lugar: "tekno01",
    categoria: "Comercios",
    portada: "/assets/logos/teknomania.svg",
    logo: "./assets/logos/teknomania.svg",
    galeria: [],
    tour: "",
  },
  "alba01": {
    nombre: "Alba Garcia",
    lugar: "alba01",
    categoria: "Comercios",
    portada: "/assets/logos/alba_garcia.svg",
    logo: "./assets/logos/alba_garcia.svg",
    galeria: [],
    tour: "",
  },
  "atila01": {
    nombre: "Atila",
    lugar: "atila01",
    categoria: "Comercios",
    portada: "/assets/logos/atila.svg",
    logo: "./assets/logos/atila.svg",
    galeria: [],
    tour: "",
  },
}

export const categorias = [
  {
    nombre: "Apart Hotel",
    coleccion: ["bahia01", "orion01", "casali14", "casali15", "casali16", "casali17"]
  },
  {
    nombre: "Propiedades",
    coleccion: ["casali11", "casali12", "casali08", "casali09", "casali06", "casali13", "casali00", "casali10", "casali01", "casali18", "casali02", "casali03", "casali04", "casali07", "casali05"]
  },
  {
    nombre: "Salones",
    coleccion: ["alem01", "top501", "top601"]
  },
  {
    nombre: "Comercios",
    coleccion: ["moto01", "iagro01"]
  }
]